nb_num: 2
data_path: /content/drive/MyDrive/kaggle_PetFinder/data
seed: 77
epoch: 50
fold_num: 5
use_fold: 0
model_arch: tf_efficientnet_b0
img_size: 256
train_bs: 32
valid_bs: 32
num_workers: 2
device: cuda:0
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
model_selection: KFold
optimizer: AdamW
lr: 1e-3
weight_decay: 1e-4
beta1: 0.5
beta2: 0.999
scheduler: OneCycleLR