data_path: /content/drive/MyDrive/kaggle_PetFinder/data
wandb_project: kaggle_PF

seed: 77

fold_num: 10
use_fold: [0]
model_arch: vit_large_patch32_384
device: cuda:0

defaults:
  - data: data
  - train: train

