nb_num: 1
data_path: /content/drive/MyDrive/kaggle_PetFinder/data
wandb_project: kaggle_PF_pre

seed: 77
epoch: 10
fold_num: 5
use_fold: 0
model_arch: tf_efficientnet_b0
train_bs: 16
valid_bs: 16
num_workers: 2
device: cuda:0

defaults:
  - aug: aug
  - train: train

