epoch: 12
model_selection: KFold
optimizer: AdamW
lr: 1e-4
loss: MSELoss # MSELoss, BCEWithLogitsLoss
weight_decay: 1e-6
beta1: 0.5
beta2: 0.999
scheduler: OneCycleLR
pct_start: 0.1
div_factor: 10.
final_div_factor: 1000.