exps: [84, 89, 91, 93, 95, 101, 113, 115, 120]
seed: 77
fold: StratifiedKFold
fold_num: 6
count: 100

model: SVR
sweep_cfg:
  metric:
    name: valid_rmse
    goal: minimize
  method: bayes
  parameters:
    C:
      values: [2, 3]
    # C:
    #   values: [2**i for i in range(-5, 11)]
    # epsilon:
    #   values: [2**i for i in range(-10, 1)]
    # gamma:
    #   values: [2**i for i in range(-20, 11)]