program: ../main.py
method: bayes
metric:
  name: valid_rmse
  goal: minimize
parameters:
  C:
    values: [2**i for i in range(-5, 11)]
  epcilon:
    values: [2**i for i in range(-10, 1)]
  gamma:
    values: [2**i for i in range(-20, 11)]